# Generated by Django 5.1 on 2024-10-31 11:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(choices=[('gpt-3.5-turbo-0125', 'GPT-3.5 Turbo 0125'), ('gpt-4o', 'GPT-4o'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4', 'GPT-4'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('claude-3-sonnet-20240229', 'Claude 3 Sonnet 20240229'), ('claude-3-haiku-20240307', 'Claude 3 Haiku 20240307'), ('claude-3-opus-20240229', 'Claude 3 Opus 20240229')], default='gpt-3.5-turbo', max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('conversation_starter', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatbot_profile_url', models.URLField(max_length=1024)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=150)),
                ('top_p', models.FloatField(default=0.9)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleDriveAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('namespace', models.CharField(max_length=500)),
                ('document_type', models.CharField(max_length=10)),
                ('k_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('google_drive_folder_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('s3_url', models.URLField(max_length=1024)),
                ('document_type', models.CharField(default='pdf', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
